import { test } from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { KEYMAN_CONTRACTS } from "../src/keyman_data.js";
import { rowsFromExport, renderConstant } from "../scripts/keyman_snapshot.mjs";

// The bundled Contract Counter is a dated SNAPSHOT of production, generated by a script — not a
// hand transcription that drifts. It only ever seeds an EMPTY table (keyman_seed_guard.test.js).
const HEADER = readFileSync(new URL("../src/keyman_data.js", import.meta.url), "utf-8").split("\n")[0];
const WORKER = readFileSync(new URL("../src/worker.js", import.meta.url), "utf-8");

test("keyman_data.js is a dated production snapshot and KEYMAN_VERSION carries the same date", () => {
  const m = HEADER.match(/SNAPSHOT of production keyman_contract3 taken (\d{4}-\d{2}-\d{2})/);
  assert.ok(m, "header must name the snapshot date");
  const v = WORKER.match(/const KEYMAN_VERSION = "(\d{4}-\d{2}-\d{2})-cc-v\d+"/);
  assert.ok(v, "KEYMAN_VERSION must be <date>-cc-v<N>");
  assert.equal(v[1], m[1], "a regenerated snapshot must bump KEYMAN_VERSION to its date");
});

test("every bundled row is well-formed and (sc, seq) is unique — the table's primary key", () => {
  assert.ok(KEYMAN_CONTRACTS.length > 0);
  const seen = new Set();
  for (const r of KEYMAN_CONTRACTS) {
    assert.match(r.sc, /^SC-\d{7}$/, "sc " + r.sc);
    assert.ok(Number.isInteger(r.seq) && r.seq >= 1, "seq " + r.seq);
    if (r.ship != null) assert.ok(typeof r.ship === "string" && r.ship.length, "ship " + r.ship);
    assert.match(r.on, /^\d{4}-\d{2}-\d{2}$/, "sign-on " + r.on);
    for (const k of ["proj", "act"]) if (r[k] != null) assert.match(r[k], /^\d{4}-\d{2}-\d{2}$/, k + " " + r[k]);
    const k = r.sc + "|" + r.seq;
    assert.ok(!seen.has(k), "duplicate (sc, seq) " + k);
    seen.add(k);
  }
  // seq gaps are LEGAL: a leg whose sign-on was unreadable is skipped (and reported) by the importer.
});

test("the generator is deterministic and accepts both a bare array and the wrangler --json envelope", () => {
  const rows = [{ sc: "SC-0000002", km: null, ship: "Icon", st: null, seq: 2, sign_on: "2026-08-01", proj_off: null, act_off: null },
    { sc: "SC-0000001", km: "12", ship: "Apex", st: "Onboard", seq: 1, sign_on: "2026-01-01", proj_off: "2026-07-01", act_off: "2026-06-30" }];
  const a = renderConstant(rowsFromExport(JSON.stringify(rows)), "2026-09-05");
  const b = renderConstant(rowsFromExport(JSON.stringify([{ results: rows, success: true }])), "2026-09-05");
  assert.equal(a, b);
  assert.match(a, /^\{sc:"SC-0000001",km:"12",ship:"Apex",st:"Onboard",seq:1,on:"2026-01-01",proj:"2026-07-01",act:"2026-06-30"\},$/m, "sorted by sc, seq; all 8 fields");
  assert.throws(() => rowsFromExport(JSON.stringify([{ sc: "SC-1", seq: 1 }])), /missing sign_on/);
  assert.equal(rowsFromExport(JSON.stringify([{ sc: "SC-1", seq: 2, sign_on: "2026-01-01", ship: "" }]))[0].ship, null, "a blank ship is legal (nullable in prod)");
});
