// Regenerate src/keyman_data.js (the bundled Contract Counter snapshot) from a D1 export.
//
// The constant exists for ONE reason: to seed an EMPTY keyman_contract3 (a fresh staging / local
// DB) so the console has contract history to render. It never touches a populated table
// (ensureKeymanImpl refuses the reseed, CLAUDE.md §11). Until 2026-09-05 it was a 2022-era
// spreadsheet transcription (209 rows) that no longer resembled production (47 rows, all seq=1),
// so a fresh database started from the wrong world. It is now a dated snapshot of production.
//
// Usage (from the repo root, with a Cloudflare token that can READ prod D1):
//   npx wrangler d1 execute cims-hr-console --remote --json \
//     --command "SELECT sc, km, ship, st, seq, sign_on, proj_off, act_off FROM keyman_contract3 ORDER BY sc, seq" \
//     > /tmp/kc3.json
//   node scripts/keyman_snapshot.mjs /tmp/kc3.json 2026-09-05
// Then bump KEYMAN_VERSION in src/worker.js to "<date>-cc-v<N>" and commit both.
// The input may be the wrangler --json envelope ([{results:[...]}]) or a bare array of rows.
import { readFileSync, writeFileSync } from "node:fs";

export function rowsFromExport(text) {
  const j = JSON.parse(text);
  const rows = Array.isArray(j) && j.length && j[0] && Array.isArray(j[0].results) ? j[0].results : j;
  if (!Array.isArray(rows)) throw new Error("expected a JSON array of rows or a wrangler --json envelope");
  return rows.map((r) => {
    // Only the PK and the column every reader filters on are required; ship/km/st are nullable in prod.
    for (const c of ["sc", "seq", "sign_on"]) if (r[c] == null || r[c] === "") throw new Error("row missing " + c + ": " + JSON.stringify(r));
    return { sc: String(r.sc), km: r.km == null ? null : String(r.km), ship: r.ship == null || r.ship === "" ? null : String(r.ship), st: r.st == null ? null : String(r.st),
      seq: Number(r.seq), on: String(r.sign_on), proj: r.proj_off == null ? null : String(r.proj_off), act: r.act_off == null ? null : String(r.act_off) };
  }).sort((a, b) => (a.sc < b.sc ? -1 : a.sc > b.sc ? 1 : a.seq - b.seq));
}

export function renderConstant(rows, date) {
  const crews = new Set(rows.map((r) => r.sc)).size;
  const lines = rows.map((r) => "{" + ["sc", "km", "ship", "st", "seq", "on", "proj", "act"].map((k) => k + ":" + JSON.stringify(r[k])).join(",") + "},");
  return [
    "// Keyman contract history — SNAPSHOT of production keyman_contract3 taken " + date + ":",
    "// " + rows.length + " rows, " + crews + " crew. Regenerated by scripts/keyman_snapshot.mjs (never by hand).",
    "// Only ever seeds an EMPTY table (ensureKeymanImpl refuses to touch a populated one). The live",
    "// data comes from the Keyman 'Contract Counter' upload on the Data page. Informational only;",
    "// NEVER affects payouts.",
    "export const KEYMAN_CONTRACTS = [",
    ...lines,
    "];",
    "",
  ].join("\n");
}

if (process.argv[1] && import.meta.url.endsWith(process.argv[1].split("/").pop())) {
  const [file, date] = process.argv.slice(2);
  if (!file || !/^\d{4}-\d{2}-\d{2}$/.test(date || "")) { console.error("usage: node scripts/keyman_snapshot.mjs <export.json> <YYYY-MM-DD>"); process.exit(2); }
  const rows = rowsFromExport(readFileSync(file, "utf-8"));
  const out = new URL("../src/keyman_data.js", import.meta.url);
  writeFileSync(out, renderConstant(rows, date), "utf-8");
  console.log("[keyman_snapshot] wrote " + rows.length + " rows to src/keyman_data.js (snapshot " + date + ")");
}
